// <auto-generated />
using AspNetCore.Localization.Localization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCore.Localization.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("AspNetCore.Localization.Localization.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("ThreeLetterIsoCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<string>("TwoLetterIsoCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            Name = "English",
                            ThreeLetterIsoCode = "eng",
                            TwoLetterIsoCode = "en"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "fr-FR",
                            Name = "French",
                            ThreeLetterIsoCode = "fre",
                            TwoLetterIsoCode = "fr"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "de-DE",
                            Name = "German",
                            ThreeLetterIsoCode = "ger",
                            TwoLetterIsoCode = "de"
                        });
                });

            modelBuilder.Entity("AspNetCore.Localization.Localization.LanguageResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3000);

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "menu.homepage",
                            LanguageId = 1,
                            Value = "Home Page"
                        },
                        new
                        {
                            Id = 2,
                            Key = "menu.homepage",
                            LanguageId = 2,
                            Value = "Page D'accueil"
                        },
                        new
                        {
                            Id = 3,
                            Key = "menu.homepage",
                            LanguageId = 3,
                            Value = "Startseite"
                        });
                });

            modelBuilder.Entity("AspNetCore.Localization.Localization.LanguageResource", b =>
                {
                    b.HasOne("AspNetCore.Localization.Localization.Language", "Language")
                        .WithMany("LanguageResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
